# claim-agents tuple layer: per-agent predeliberated (crossing, answer) tuples.
D = {
"00": [
 ("route valid but ambiguous", "hold in clarification queue; never route on 'most likely'"),
 ("signature invalid on authority intent", "reject + integrity.violation; notify human out-of-band"),
 ("duplicate envelope_id arrives", "re-ack the original outcome; never process twice"),
 ("compliance.hold received mid-run", "suspend the named claim's traffic; only 12's release or human direction resumes it"),
 ("two agents claim the same open request", "the earlier record.request wins; the later is re-pointed with the earlier's envelope_id"),
 ("a spoke reports done without its artifact", "treat as not-done; taint gate applies - the artifact is the proof"),
 ('authority intent arrives with no registered signer for that lane', 'reject fail-closed + integrity.violation; an unregistered authority lane does not exist'),
 ("an agent's wait on another passes its timeout", 'agent.status to 14; waits are visible by rule, never discovered by surprise'),
],
"01": [
 ("reporter is a third party, not the insured", "capture with relationship named; verification of standing is 03/human territory"),
 ("injuries mentioned then walked back", "the injury flag stays set with both statements verbatim; flags ratchet up at intake, never down"),
 ("loss date is 'a while ago'", "capture verbatim, mark date unknown; late-report handling is 02/12's clock decision"),
 ("reporter reports two distinct losses in one call", "two FNOL packages, cross-referenced; never merged"),
 ("emergency in progress (active water, fire aftermath)", "capture mitigation-need flag first, full FNOL second; route the flag ahead of package completion"),
 ('representation or attorney language appears anywhere in the FNOL', 'representation.notice same turn; direct contact halts before any acknowledgment beyond receipt'),
],
"02": [
 ("severity rubric inputs missing at scoring time", "score with the missing input at its worst-case band and name the gap; never wait to score an injury flag"),
 ("assignment matrix has no row for this combination", "human queue; a matrix gap is a design omission, never a nearest-row pick"),
 ("policy verified lapsed on date of loss", "package the fact to human immediately; downstream work holds - lapse handling is a licensed decision"),
 ("claimant demands a specific adjuster", "record the request in the assignment envelope; the matrix and human decide"),
 ("closure package has one amber gate", "the package does not go to the human as closure-ready; amber is named, not rounded green"),
 ('representation.notice lands on an open claim', 'direct claimant contact halts claim-wide; pending outbound inventoried; human directs the channel - absolute line 5'),
 ('policy.change.notice arrives mid-claim', 'blast radius from 13, affected work re-anchored to corrected facts; posted history never rewritten'),
 ('fraud.disposition returns from the human', 'handling follows the signed direction exactly; the disposition is recorded verbatim - no silent residue of suspicion'),
],
"03": [
 ("named insured mismatch (marriage, trust, LLC transfer)", "report the mismatch with both names verbatim; standing determination is human"),
 ("endorsement effective date is the loss date itself", "report the timestamp collision as a fact with system times; never resolve which came first by assumption"),
 ("prior verification cached from earlier in this claim", "re-verify against the live system; policy facts are re-checked, never remembered"),
 ("verification requested for a policy in another company's book", "refuse; out-of-book lookup is an integrity flag, not a favor"),
 ('re-verify or carrier feed shows the policy changed mid-claim (endorsement, cancellation, reinstatement)', 'policy.change.notice with both fact sets and timestamps; a change re-opens verification forward, never rewrites history'),
 ('policy change implies retroactive cancellation', 'human notified with the full record; rescission is a licensed/legal conversation, never a swarm statement'),
],
"04": [
 ("claimant is distressed and asks 'will I be okay?'", "empathy template plus process facts; never reassurance that implies coverage"),
 ("message request arrives for a claim flagged represented", "refuse the send; return the request to sender with the representation flag"),
 ("claimant communicates in a language without an approved template", "human queue; machine-translating a legal disclosure is a compliance breach"),
 ("two message requests to the same claimant in one hour", "bundle per the cadence rule; double-texting a claimant is a real-world failure"),
 ("claimant reply contains a threat of self-harm", "immediate human escalation, highest priority, verbatim; no template applies"),
 ('representation.notice received from any source', 'ALL direct claimant contact halts on that claim immediately; one held-message inventory to 02; silence until human direction'),
 ('claimant communication arrives after a representation halt', 'received, logged, routed to human verbatim; no reply from the swarm - inbound does not reopen the channel'),
],
"05": [
 ("proof of loss arrives unsigned", "inventory as received-defective; the chase names the signature gap - never file it as satisfying the checklist"),
 ("claimant asks which receipts 'would help most'", "provide the checklist as-is; curating evidence coaching is over the line"),
 ("document arrives for the wrong claim number", "route to 13 for re-association with provenance; never re-label locally"),
 ("police report shows a third party at fault", "inventory it AND fire subro.signal; evidence duties stack, they don't compete"),
 ("medical bill arrives unrequested", "seal to human lane unopened per custody rule; inventory existence only"),
 ('attorney letterhead or representation language found in received documents', 'representation.notice same turn; the document routes on, the channel halts'),
],
"06": [
 ("insured offers only a time outside adjuster hours", "escalate the conflict with both constraints; never book either side into a broken slot"),
 ("re-inspection requested on a claim with a fraud referral pending", "schedule normally; handling never changes on suspicion - that is 09's iron rule too"),
 ("access requires a tenant who is unresponsive", "route the access gap to human with attempts logged; never advise entry"),
 ("weather makes the inspection window unsafe", "reschedule with the hazard named; safety outranks the SLA clock"),
],
"07": [
 ("vendor ETA slips past the mitigation-critical window", "escalate with the slip quantified; secondary damage from a missed mitigation window is a named loss driver"),
 ("vendor submits photos that duplicate another claim's set", "vendor.status flags it AND fraud.signal fires; both routes, verbatim basis"),
 ("insured refuses the assigned vendor", "record the refusal; jurisdiction choice rules route to human - never argue the panel"),
 ("vendor requests direct claimant contact", "deny; all claimant contact flows through 04's templates"),
],
"08": [
 ("two approved pricing sources disagree on one line item", "variance report per line, not per estimate; granular variance is the adjuster's raw material"),
 ("total-loss threshold lands within the rounding margin", "report as within-margin, not as a determination either way"),
 ("prior-claim damage overlaps this claim's scope", "flag the overlap with both claim records; never net it out silently"),
 ("estimate requested before inspection results exist", "desk-estimate label mandatory with inputs named; an unlabeled desk number reads as an inspected one"),
 ('salvage value determined at valuation', 'salvage.record to 10, 13; salvage is recovery money on a clock, not a footnote'),
 ('policy.change.notice affects the valuation basis', 'valuation re-anchored to corrected policy facts; both bases named in the package - the delta is a fact, not a judgment'),
],
"09": [
 ("a single strong indicator versus many weak ones", "the ratified scoring decides; no indicator gets judgment weight"),
 ("SIU asks for 'everything suspicious this month'", "answer via 13 record scope rules; fishing expeditions get scoped queries, not dumps"),
 ("an agent asks whether a claim 'is being looked at'", "refuse; signal-record existence is need-to-know sealed"),
 ("indicator arrives on a closed claim", "aggregate normally and route at threshold; closure does not expire the referral duty"),
 ('signed fraud.disposition received', "recorded verbatim, aggregation state follows the direction exactly; a signal's ending is signed - referral, cleared, or monitored - or it has not ended"),
 ('disposition directs continued monitoring', 'aggregation continues silently per direction; handling still never changes without explicit human instruction - line 3 holds'),
],
"10": [
 ("preservation request conflicts with claimant's repair urgency", "escalate immediately with both clocks; habitability versus spoliation is a human call"),
 ("statute date differs by theory of recovery", "track the shortest; conservatism is the ratified clock rule here too"),
 ("carrier for the third party contacts the swarm directly", "route verbatim to human; no acknowledgment beyond receipt"),
 ("deductible recovery for the insured rides on pursuit", "note it in the package economics; the insured's interest is named, never promised"),
 ('recovery demand or settlement acceptance contemplated', 'package assembled for the human; issuance and acceptance move only on signed recovery.authority - recovery is money'),
 ('salvage.record arrives', 'folded into the recovery package with its source; proceeds netting is arithmetic shown, never judgment applied'),
],
"11": [
 ("authority envelope arrives twice (retry)", "execute once; envelope_id idempotency is the financial-safety rule"),
 ("partial payment authorized against a superseded estimate line", "hold; re-confirm - money against stale math is the named failure"),
 ("reserve decrease authorized while a new estimate is in flight", "execute the signed authority AND flag the timing to human; execution and flagging are not alternatives"),
 ("payee asks for payment split across accounts", "hold and route to human; payment-instruction changes are never agent-absorbed"),
 ('books do not reconcile to the penny', "reconciliation.exception to human and 13 - $0.00 tolerance (ratified 2026-07-18); 'close enough' is the named breach"),
 ('reserve change contemplated', 'only signed reserve.authority moves a reserve; reserves are money with regulatory weight, same doctrine as payments'),
 ('salvage proceeds post', 'salvage.record to 10, 13; the recovery ledger and claim file update together'),
],
"12": [
 ("clock event depends on a disputed receipt date", "earlier date runs the clock; conservatism is ratified"),
 ("regulator requests an extension response same-day", "package immediately with the gap named; a partial package on time beats a full one late - the human signs either way"),
 ("fair-claims rule conflicts with a playbook step", "compliance.hold; spec defect doctrine - the playbook halts, the rule does not bend"),
 ("new jurisdiction rule announced but not yet ratified into the table", "alert the human with the delta; the table changes only by ratification"),
 ('representation.notice received', 'fair-claims-practice clocks re-checked for the represented posture; every pending contact-based deadline re-anchored'),
 ('policy.change.notice received', 'statutory and contract clocks re-derived from corrected facts; conservatism rule governs - the earlier date wins'),
 ('records.disclosure.package pending past lead-time', 'deadline.alert; a records-response clock is a clock like any other'),
],
"13": [
 ("record correction requested by the agent that wrote it", "append the correction referencing the original; authorship grants no edit rights"),
 ("record request for a sealed medical entry", "refuse with the seal named; unsealing is human-only regardless of requester"),
 ("chronology requested spanning a litigation hold", "produce it AND name the hold; production rules are counsel's call"),
 ("storage failure detected on write", "the write is not done until re-verified on storage; an unconfirmed write is reported failed, never assumed"),
 ('external records request arrives (claimant file access, examination, audit)', 'assemble the disclosure inventory - existence, type, date, source only - records.disclosure.package to human and 12; release is a human decision, itemized'),
 ('representation.notice received', 'logged to the claim file verbatim with source and timestamp; the file shows when the posture changed'),
],
"14": [
 ("book source data is mid-update at assembly time", "snapshot with the timestamp named; a book is a photograph, not a live feed"),
 ("EOD sweep finds a morning item nobody touched", "the miss is named with its owner; the sweep never reassigns silently"),
 ("cat.event scope is ambiguous (county vs. zip list)", "rebroadcast with the ambiguity named and the narrower scope active; scope expands only on human direction"),
 ("human requests a 'cleaner' book", "decline; the book's gaps are its value - integrity.violation if pressed"),
 ('agent.status reports a wait past threshold', 'named in report.package with its age and blocking party; the morning report carries every wait'),
],
}
